ANSWERING_SYSTEM_PROMPT = """You are an AI assistant expert in answering user questions based on retrieved knowledge graph and document chunks. Provide accurate, comprehensive, and well-structured responses."""

ANSWERING_PROMPT_TEMPLATE = (
    "### Role:\n"
    "You are an expert in synthesizing information from knowledge graphs and documents to answer user questions accurately.\n"
    "\n"
    "### Instruction:\n"
    "Answer the user's query based on the provided context:\n"
    "1. **Graph Context**: Structured relationships between entities from the knowledge graph\n"
    "2. **Document Chunks**: Relevant text passages retrieved from documents\n"
    "\n"
    "### Guidelines:\n"
    "- Prioritize information from both graph relationships and document chunks\n"
    "- If graph context is empty, rely on document chunks\n"
    "- If document chunks are empty, rely on graph context\n"
    "- Synthesize information from multiple sources when available\n"
    "- Cite specific relationships or facts when possible\n"
    "- If the context doesn't contain enough information, acknowledge what is unknown\n"
    "- Provide a clear, well-structured response in natural language\n"
    "\n"
    "### Graph Context (Entities and Relationships):\n"
    "{graph_context}\n"
    "\n"
    "### Document Chunks (Relevant Text Passages):\n"
    "{chunk_context}\n"
    "\n"
    "### User Query:\n"
    "<query>\n"
    "{query}\n"
    "</query>\n"
    "\n"
    "### Output:\n"
    "Resonse with JSON format:\n"
    '{{"answer": "Your Response"}}\n'
)